export const data = [
  {
    id: 6,
    img: "https://res.cloudinary.com/diyky5uya/image/upload/v1651179636/ytclone_uuueoy.png",
    host: "https://clonetube1.netlify.app/",
    title: "YouTube clone",
    github: "https://github.com/levaniakobidze/Youtube-Clone",
  },
  {
    id: 9,
    img: "https://res.cloudinary.com/diyky5uya/image/upload/v1652800332/country_dcbmzo.png",
    host: "https://country123.netlify.app//",
    title: "Search country",
    github: "https://github.com/levaniakobidze/Country-search-API",
  },
  {
    id: 8,
    img: "https://res.cloudinary.com/diyky5uya/image/upload/v1653212597/quiiz_ckvfzn.png",
    host: "https://levanquiz.netlify.app/",
    title: "Quiz",
    github: "https://github.com/levaniakobidze/Quiz_api",
  },
  {
    id: 5,
    img: "https://res.cloudinary.com/diyky5uya/image/upload/v1650572253/todoo_zt2uiz.png",
    host: "https://todo-app-with-react12.netlify.app/",
    title: "Todo-App",
    github: "https://github.com/levaniakobidze/React-Todo-app",
  },
  {
    id: 2,
    img: "https://res.cloudinary.com/diyky5uya/image/upload/v1649954893/users_q4ebfs.png",
    host: "https://githubsearch12.netlify.app/",
    title: "Users search",
    github: "https://github.com/levaniakobidze/Github-Users",
  },
  {
    id: 7,
    img: "https://res.cloudinary.com/diyky5uya/image/upload/v1651425412/traff11_niyc3h.png",
    host: "https://ltrafalgar.netlify.app/",
    title: "Landing page",
    github: "https://github.com/levaniakobidze/trafalgar-landing-page",
  },
  {
    id: 1,
    img: "https://res.cloudinary.com/diyky5uya/image/upload/v1649954772/landing_v1fmpo.png",
    host: "https://travel-page1.netlify.app/",
    title: "Travel page",
    github: "https://github.com/levaniakobidze/Travel-page",
  },

  {
    id: 3,
    img: "https://res.cloudinary.com/diyky5uya/image/upload/v1650569021/landing-page_fcq4fi.png",
    host: "https://landingpage1223.netlify.app/",
    title: "Landing page",
    github: "https://github.com/levaniakobidze/Landing-page",
  },
  {
    id: 4,
    img: "https://res.cloudinary.com/diyky5uya/image/upload/v1650570209/quotes_wqtojq.png",
    host: "https://quotes-generator12.netlify.app/",
    title: "Quotes generator",
    github: "https://github.com/levaniakobidze/React-Random-Quotes",
  },
];

export const moreData = [
  {
    id: 6,
    img: "https://res.cloudinary.com/diyky5uya/image/upload/v1651179636/ytclone_uuueoy.png",
    host: "https://clonetube1.netlify.app/",
    title: "YouTube clone",
    github: "https://github.com/levaniakobidze/Youtube-Clone",
  },
  {
    id: 9,
    img: "https://res.cloudinary.com/diyky5uya/image/upload/v1652800332/country_dcbmzo.png",
    host: "https://country123.netlify.app//",
    title: "Search country",
    github: "https://github.com/levaniakobidze/Country-search-API",
  },
  {
    id: 8,
    img: "https://res.cloudinary.com/diyky5uya/image/upload/v1653212597/quiiz_ckvfzn.png",
    host: "https://levanquiz.netlify.app/",
    title: "Quiz",
    github: "https://github.com/levaniakobidze/Quiz_api",
  },
  {
    id: 5,
    img: "https://res.cloudinary.com/diyky5uya/image/upload/v1650572253/todoo_zt2uiz.png",
    host: "https://todo-app-with-react12.netlify.app/",
    title: "Todo-App",
    github: "https://github.com/levaniakobidze/React-Todo-app",
  },
  {
    id: 2,
    img: "https://res.cloudinary.com/diyky5uya/image/upload/v1649954893/users_q4ebfs.png",
    host: "https://githubsearch12.netlify.app/",
    title: "Users search",
    github: "https://github.com/levaniakobidze/Github-Users",
  },
  {
    id: 7,
    img: "https://res.cloudinary.com/diyky5uya/image/upload/v1651425412/traff11_niyc3h.png",
    host: "https://ltrafalgar.netlify.app/",
    title: "Landing page",
    github: "https://github.com/levaniakobidze/trafalgar-landing-page",
  },
  {
    id: 1,
    img: "https://res.cloudinary.com/diyky5uya/image/upload/v1649954772/landing_v1fmpo.png",
    host: "https://travel-page1.netlify.app/",
    title: "Travel page",
    github: "https://github.com/levaniakobidze/Travel-page",
  },

  {
    id: 3,
    img: "https://res.cloudinary.com/diyky5uya/image/upload/v1650569021/landing-page_fcq4fi.png",
    host: "https://landingpage1223.netlify.app/",
    title: "Landing page",
    github: "https://github.com/levaniakobidze/Landing-page",
  },
  {
    id: 4,
    img: "https://res.cloudinary.com/diyky5uya/image/upload/v1650570209/quotes_wqtojq.png",
    host: "https://quotes-generator12.netlify.app/",
    title: "Quotes generator",
    github: "https://github.com/levaniakobidze/React-Random-Quotes",
  },
];
